config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/create'

  get 'password_resets/edit'

  get 'password_resets/update'

  get 'oauths/oauth'

  get 'oauths/callback'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
# ==============================================================================================
# Static Pages
# ==============================================================================================

root to: "pages#index"

get 'user_profile/verification' => 'user_profiles#verification'
post 'user_profile/verification' => 'user_profiles#check_pin_code'

# ==============================================================================================
# Resource
# ==============================================================================================

resources :users, only: [:new, :create, :show, :index, :edit, :update] 

resources :user_profiles, only: [:new, :create, :edit, :update]

resources :agent_profiles, only: [:new, :create, :edit, :update]

resources :requests, only: [:new, :create, :edit, :update, :index]

resources :password_resets

# ==============================================================================================
# User Sessions/Login/Logout
# ==============================================================================================

resources :user_sessions, only: [:new, :create]

get :login, to: 'user_sessions#new'
delete :logout, to: 'user_sessions#destroy'


# ==============================================================================================
# API for Ionic App
# ==============================================================================================

namespace :api do
    namespace :v1 do
      resources :users, only: [:create, :show, :index, :update]
      resources :user_sessions, only: [:create]
      resources :agent_profile, only: [:create]

      post '/agent_profile/send_pin_code' => 'agent_profile#send_pin_code'
      post '/agent_profile/verify_pin_code' => 'agent_profile#verify_pin_code'
      post '/agent_profile/upload_photo' => 'agent_profile#upload_photo'
      patch '/agent_profile/update_profile' => 'agent_profile#update_profile'
    end
end



post "oauth/callback" => "oauths#callback"
get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :all
       else
         can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_listing.rb
class AdminListing < ActiveRecord::Base
	mount_uploader :avatar, AvatarUploader
end

app/models/agent_profile.rb
class AgentProfile < ActiveRecord::Base
  belongs_to :user
end

app/models/area.rb
class Area < ActiveRecord::Base
	has_many :locations
	has_many :requests
	has_many :listings
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
end

app/models/instruction.rb
class Instruction < ActiveRecord::Base
	mount_uploader :avatar, AvatarUploader
end

app/models/listing.rb
class Listing < ActiveRecord::Base
	belongs_to :user
	belongs_to :area
	belongs_to :location

	enum status: [:active, :publish]
	enum rent_sale: [:rent, :sale]
	enum house_condo: [:house, :condo]
	enum pet_friendly: [:yes, :no]

	#rails_admin do
	#  object_label_method :area_name
	#  object_label_method :location_name
	#end


	#def area_name
	#  a = Area.find(self.area_id)
	#  return a.area
	#end

	#def location_name
	#  l = Location.find(self.location_id)
	#  return l.location
	#end
end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :area
	#has_many :requests
	#has_many :listings

	#rails_admin do
	 # object_label_method :area_name
	#end


	#def area_name
	 # a = Area.find(self.area_id)
	 # return a.area
	#end
end

app/models/media_coverage.rb
class MediaCoverage < ActiveRecord::Base
	mount_uploader :avatar, AvatarUploader
end

app/models/request.rb
class Request < ActiveRecord::Base
	belongs_to :user
	belongs_to :area
	belongs_to :location

	validates :area_id, presence: true
	validates :no_of_rooms, presence: true
	validates :budget_min, presence: true
	validates :budget_max, presence: true

	rails_admin do
	  object_label_method :area_name
	  object_label_method :location_name
	end


	def area_name
	  a = Area.find(self.area_id)
	  return a.area
	end

	def location_name
	  l = Location.find(self.location_id)
	  return l.location
	end
end

app/models/user.rb
class User < ActiveRecord::Base

  authenticates_with_sorcery!
  
  has_one :agent_profile, dependent: :destroy
  has_many :requests, dependent: :destroy
  has_one :user_profile, dependent: :destroy

  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications
  accepts_nested_attributes_for :user_profile

  validates :password, length: { minimum: 8 }, if: :password
  validates :password, confirmation: true, if: :password
  validates :password_confirmation, presence: true, if: :password

  enum role: [:user, :agent, :admin]
  enum status: [:active, :inactive]
  
  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)
    return user if user 
    false
  end

  def generate_auth_token
    payload = { user_id: id }
    AuthTokenService.encode(payload)
  end
end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
  belongs_to :user
  
  mount_uploader :avatar, AvatarUploader

  validates_uniqueness_of :contact_no
  validates :contact_no, presence: true
  validates :first_name, presence: true
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/oauths_helper.rb
module OauthsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_profile_helper.rb
module UserProfileHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
  title ConnectMalaysia
  meta content="initial-scale=1" name="viewport"
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': false
  = javascript_include_tag 'application', 'data-turbolinks-track': false
  = csrf_meta_tags

  //! Google Fonts
  link href="http://fonts.googleapis.com/css?family=Rochester" rel="stylesheet" type="text/css"
  link href="http://fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet" type="text/css"

  body
    = render "pages/partials/header"
    #page
      = yield
    footer
      = render "pages/partials/footer"
    = render "shared/log_in"
    = render "shared/sign_up"

app/views/pages/index.html.erb
<!-- Begin Main -->
<div role="main" class="main">
	<!-- Begin Main Slide -->
	<%= render 'pages/partials/slider' %>
	<!-- End Main Slide -->

	<!-- Begin Advanced Search -->
	<%= render 'pages/partials/search' %>
	<!-- End Advanced Search -->
	
	<!-- Begin Featured -->
	<%= render 'pages/partials/featured' %>
	<!-- End Featured -->
	
	<!-- Begin Properties -->
	<%= render 'pages/partials/properties' %>
	<!-- End Properties -->
	
	<!-- Begin About -->
	<%= render 'pages/partials/about' %>
	<!-- End About -->
	
</div>
<!-- End Main -->

app/views/pages/partials/_about.html.slim
section.pgl-about
  .container
    .row
      .col-md-4.animation.about-item
        h2 Who We Are
        p
          img.img-responsive src="assets/event1.jpg"
        p We have a total of 25+ years combined experience dealing exclusively with New York buyers and sellers ipsum dolor sit amet, consectetur adipiscing elit.
        a.btn.btn-lg.btn-default href="about-us.html"  View more
      .col-md-4.animation.about-item
        h2 Why Choose Us
        #accordion.panel-group
          .panel.panel-default.pgl-panel
            .panel-heading
              h4.panel-title
                a data-parent="#accordion" data-toggle="collapse" href="#collapseOne"  Reliability
            #collapseOne.panel-collapse.collapse.in
              .panel-body
                p Sed perspiciatis unde omnisiste natus error voluptatem remopa accusantium doloremque laudantium, totam rem aperiam.
          .panel.panel-default.pgl-panel
            .panel-heading
              h4.panel-title
                a.collapsed data-parent="#accordion" data-toggle="collapse" href="#collapseTwo"  Quality
            #collapseTwo.panel-collapse.collapse
              .panel-body
                p Sed perspiciatis unde omnisiste natus error voluptatem remopa accusantium doloremque laudantium, totam rem aperiam.
          .panel.panel-default.pgl-panel
            .panel-heading
              h4.panel-title
                a.collapsed data-parent="#accordion" data-toggle="collapse" href="#collapseThree"   Flexible
            #collapseThree.panel-collapse.collapse
              .panel-body
                p Sed perspiciatis unde omnisiste natus error voluptatem remopa accusantium doloremque laudantium, totam rem aperiam.
          .panel.panel-default.pgl-panel
            .panel-heading
              h4.panel-title
                a.collapsed data-parent="#accordion" data-toggle="collapse" href="#collapseFouth"  Compatible
            #collapseFouth.panel-collapse.collapse
              .panel-body
                p Sed perspiciatis unde omnisiste natus error voluptatem remopa accusantium doloremque laudantium, totam rem aperiam.
          .panel.panel-default.pgl-panel
            .panel-heading
              h4.panel-title
                a.collapsed data-parent="#accordion" data-toggle="collapse" href="#collapseFive"  Unique
            #collapseFive.panel-collapse.collapse
              .panel-body
                p Sed perspiciatis unde omnisiste natus error voluptatem remopa accusantium doloremque laudantium, totam rem aperiam.
      .col-md-4.animation.about-item
        h2 Happy Clients
        .owl-carousel.pgl-bg-dark.pgl-testimonial data-plugin-options='{"items": 1, "pagination": false, "autoHeight": true}'
          .col-md-12
            .testimonial-author
              .img-thumbnail-small.img-circle
                img.img-circle alt=("Andrew MCCarthy") src="assets/suki2.jpg"
              h4 Suki
              p
                strong Mentee
            .divider-quote-sign
              span “
            blockquote.testimonial
              p Sed perspiciatis unde omnisiste natus error voluptatem remopa accusantium doloremque laudantium totam rem.
          .col-md-12
            .testimonial-author
              .img-thumbnail-small.img-circle
                img.img-circle alt=("John Smith") src="holder.js/110x110"
              h4 John Smith
              p
                strong Selller
            .divider-quote-sign
              span “
            blockquote.testimonial
              p Sed perspiciatis unde omnisiste natus error voluptatem remopa accusantium doloremque laudantium totam rem.

app/views/pages/partials/_featured.html.erb
<section class="pgl-featured pgl-bg-grey">
			<div class="container">
				<h2>Past Events</h2>
					<div class="row">
						<div class="col-md-6 animation">
							<div class="pgl-property featured-item">
								<div class="property-thumb-info">
									<div class="property-thumb-info-image">
										<img alt="" class="img-events" src="assets/event1.jpg">
									</div>
									<div class="property-thumb-info-content">
										<h3><a href="property-detail.html">Partnered with Startup Weekend</a></h3>
										<p>A lot of our mentors are there, lorem ipsum.</p>
									</div>
								</div>
							</div>
						</div>
						<div class="col-md-6 animation">
							<div class="pgl-property featured-item">
								<div class="property-thumb-info">
									<div class="property-thumb-info-image">
										<img alt="" class="img-events" src="assets/event2.jpg">
									</div>
									<div class="property-thumb-info-content">
										<h3><a href="property-detail.html">Partnered with Startup Weekend</a></h3>
										<p>Amet luctus nisl tempus.</p>
									</div>
								</div>
							</div>
						</div>
						<div class="col-md-6 animation">
							<div class="pgl-property featured-item">
								<div class="property-thumb-info">
									<div class="property-thumb-info-image">
										<img alt="" class="img-events" src="assets/event3.jpg">
									</div>
									<div class="property-thumb-info-content">
										<h3><a href="property-detail.html">Partnered with Next Academy</a></h3>
										<p>Amet luctus nisl tempus.</p>
									</div>
								</div>
							</div>
						</div>
						<div class="col-md-6 animation">
							<div class="pgl-property featured-item">
								<div class="property-thumb-info">
									<div class="property-thumb-info-image">
										<img alt="" class="img-events" src="assets/event4.jpg">
									</div>
									<div class="property-thumb-info-content">
										<h3><a href="property-detail.html">Partnered with Next Academy</a></h3>
										<p>Amet luctus nisl tempus.</p>
									</div>
								</div>
							</div>
						</div>
						
					</div>
					<hr class="top-tall">
				</div>
			</section>

app/views/pages/partials/_footer.html.erb
<footer class="pgl-footer">
  <div class="container">
    <div class="pgl-upper-foot">
      <div class="row">
        <div class="col-sm-4">
          <h2>Contact detail</h2>
          <p>Pellentesque nec erat. Aenean semper, neque non faucis. Malesuada, dui felis tempor felis, vel varius ante diam ut mauris.</p>
          <address>
            <i class="fa fa-map-marker"></i> Office : 1-800-666-8888<br>
            <i class="fa fa-phone"></i> Mobile : 0800-666-6666<br>
            <i class="fa fa-fax"></i> Fax : 1-800-666-8888<br>
            <i class="fa fa-envelope-o"></i> Mail: <a href="mailto:pixelgeklab@gmail.com">rachel@connectmalaysia.com</a>
          </address>
        </div>
        <div class="col-sm-2">
          <h2>Useful links</h2>
          <ul class="list-unstyled">
            <li><a href="#">Help and FAQs</a></li>
            <li><a href="#">Free Credit Report</a></li>
            <li><a href="#">Terms and Conditions</a></li>
            <li><a href="#">Privacy Policy</a></li>
            <li><a href="#">Community Guidelines</a></li>
          </ul>
        </div>
        <div class="col-sm-2">
          <h2>Pages</h2>
          <ul class="list-unstyled">
            <li><a href="#">About Us</a></li>
            <li><a href="#">Blogs</a></li>
            <li><a href="#">Contact Us</a></li>
            <li><a href="#">Advanced Search</a></li>
          </ul>
        </div>
        <div class="col-sm-4">
          <h2>Apply to be a mentor</h2>
          <p>In venenatis neque a eros laoreet eu placerat erat suscipit. Fusce cursus, erat ut scelerisque condimentum, quam odio ultrices leo.</p>
          <form class="form-inline pgl-form-newsletter" role="form">
            <div class="form-group">
              <label class="sr-only" for="exampleInputEmail2">Email address</label>
              <input type="email" class="form-control" id="exampleInputEmail2" placeholder="Enter your email here">
            </div>
            <button type="submit" class="btn btn-submit"><i class="icons icon-submit"></i></button>
          </form>
        </div>
      </div>
    </div>
    <div class="pgl-copyrights">
      <p>Copyright © 2016 ConnectMalaysia</p>
    </div>
  </div>
</footer>

app/views/pages/partials/_header.html.slim
header
  #top
    .container
      p.pull-left.text-note.hidden-xs
        i.fa.fa-phone
        | Need Support? 1-800-666-8888
      ul.nav.nav-pills.nav-top.navbar-right
        li.login
          a href="javascript:void(0);" 
            i.fa.fa-user
        li
          a data-original-title="Email" data-placement="bottom" data-toggle="tooltip" href="#" title="" 
            i.fa.fa-envelope-o
        li
          a data-original-title="Facebook" data-placement="bottom" data-toggle="tooltip" href="#" title="" 
            i.fa.fa-facebook
        li
          a data-original-title="Twitter" data-placement="bottom" data-toggle="tooltip" href="#" title="" 
            i.fa.fa-twitter
        li
          a data-original-title="Google+" data-placement="bottom" data-toggle="tooltip" href="#" title="" 
            i.fa.fa-google-plus
  nav.navbar.navbar-default.pgl-navbar-main role="navigation" 
    .container
      .navbar-header
        button.navbar-toggle data-target=".navbar-collapse" data-toggle="collapse" type="button" 
          span.sr-only Toggle navigation
          span.icon-bar
          span.icon-bar
          span.icon-bar
        a href="/"
          img.ing-logo src="/assets/logo.png" 
      .navbar-collapse.collapse.width
        ul.nav.navbar-nav.pull-right
          li.dropdown
            a.dropdown-toggle data-target="#" data-toggle="dropdown" href="index.html"  Events
            ul.dropdown-menu
              li
                a href="#{requests_path}"  All Events
              li
                a href="/"  Recommended Events

          - if current_user
            li
              a.dropdown-toggle data-toggle="dropdown" href="/"  Mentee
            li
              a.dropdown-toggle data-toggle="dropdown" href="#{users_path}"  Mentor
            li
              a.dropdown-toggle data-toggle="dropdown" href="#{user_path(current_user)}" Profile
            li 
              = link_to "Logout", "#", method: :delete
          - else
            li 
              button type="button" class="btn btn-default" data-toggle="modal" data-target="#register-modal" Sign Up
            li 
              button type="button" class="btn btn-default" data-toggle="modal" data-target="#signup-modal" Log In

app/views/pages/partials/_properties.html.erb
<section class="pgl-properties pgl-bg-grey">
				<div class="container">
					<h2>Mentors</h2>
					<!-- Nav tabs -->
					<ul class="nav nav-tabs pgl-pro-tabs text-center animation" role="tablist">
						<li class="active"><a href="#all" role="tab" data-toggle="tab">All</a></li>
						<li><a href="#house" role="tab" data-toggle="tab">Business</a></li>
						<li><a href="#offices" role="tab" data-toggle="tab">Finance</a></li>
						<li><a href="#apartment" role="tab" data-toggle="tab">Developer</a></li>
						<li><a href="#residential" role="tab" data-toggle="tab">Designer</a></li>
					</ul>

					<!-- Tab panes -->
					<div class="tab-content">
						<div class="tab-pane active" id="all">
							<div class="row">
								<div class="col-xs-4 animation">
									<div class="pgl-property">
										<div class="property-thumb-info">
											<div class="property-thumb-info-image">
												<img class="img-responsive" src="assets/cheylyeoh.png">
											</div>
											<div class="property-thumb-info-content">
												<h3><a href="property-detail.html">Cheryl Yeoh</a></h3>
												<address>Cheryl is a resourceful and versatile entrepreneur who looks to create meaningful impact with her products and is also passionate about helping other entrepreneurs.</address>
											</div>
										</div>
									</div>
								</div>
								<div class="col-xs-4 animation">
									<div class="pgl-property">
										<div class="property-thumb-info">
											<div class="property-thumb-info-image">
												<img class="img-responsive" src="assets/tony.jpg">
											</div>
											<div class="property-thumb-info-content">
												<h3><a href="property-detail.html">Tony Fernandes</a></h3>
												<address>Tony Fernandes,is a Malaysian entrepreneur. He is the founder of Tune Air Sdn. Bhd., who introduced the first budget no-frills airline, AirAsia, to Malaysians with the tagline "Now everyone can fly".</address>
											</div>
										</div>
									</div>
								</div>
								<div class="col-xs-4 animation">
									<div class="pgl-property">
										<div class="property-thumb-info">
											<div class="property-thumb-info-image">
												<img class="img-responsive" src="assets/khaileeng.jpg">
											</div>
											<div class="property-thumb-info-content">
												<h3><a href="property-detail.html">Khailee Ng</a></h3>
												<address>Tech startup investor and founder. Managing Partner, 500 Startups. Co-founder of GroupsMore (acquired by Groupon) and SAYS.com (IPO:REV).</address>
											</div>
										</div>
									</div>
								</div>
							</div>
							</div>
						</div>
					</div>
					
				</div>
			</section>

app/views/pages/partials/_search.html.slim
section.pgl-advanced-search.pgl-bg-light
  .container
    form name="advancedsearch" 
      .form-item
        .form-row
          .col-xs-12
            .form-group
              label.sr-only for="search-bedrooms"  Find an event
              select#search-bedrooms.chosen-select data-placeholder="Bedrooms" name="search-bedrooms" 
                option selected="selected" value="Bedrooms"  Startup
                option value="0"  Community
                option value="1"  Building
                option value="2"  Developing
                option value="3"  Startup
                option value="4"  Some stuff
                option value="5"  Another Event
          .col-xs-6.col-sm-3
            .form-group
              button.btn.btn-block.btn-primary type="submit"  Find Now

app/views/pages/partials/_slider.html.erb
<section class="main-slide">
		<div id="owl-main-slide" class="owl-carousel pgl-main-slide" data-plugin-options='{"autoPlay": true}'>
			<div class="item" id="item1"><img src="assets/slide1.jpg" alt="Photo" class="img-slide" height="800">
				<div class="item-caption">
					<div class="container">
						<div class="property-info">
							<div class="property-thumb-info-content">
								<h2><a href="property-detail.html">Meaningful Purpose</a></h2>
								<p>Sed perspiciatis unde omnisiste natus error voluptatem remopa accusantium doloremque laudantium, totam rem aperiam.</p>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="item" id="item2"><img src="assets/slide2.png" alt="Photo" class="img-slide" height="800">
				<div class="item-caption">
					<div class="container">
						<div class="property-info">
							<div class="property-thumb-info-content">
								<h2><a href="property-detail.html">Valuable Time</a></h2>
								<p>Sed perspiciatis unde omnisiste natus error voluptatem remopa accusantium doloremque laudantium, totam rem aperiam.</p>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="item" id="item3"><img src="assets/slide3.jpg" alt="Photo" class="img-slide" height="800">
				<div class="item-caption">
					<div class="container">
						<div class="property-info">
							<div class="property-thumb-info-content">
								<h2><a href="property-detail.html">Real Experiences</a></h2>
								<p>Sed perspiciatis unde omnisiste natus error voluptatem remopa accusantium doloremque laudantium, totam rem aperiam.</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

app/views/shared/_log_in.html.slim
#signup-modal.modal.fade tabeindex="-1" role="dialog"
  .modal-dialog role="document"
      .modal-content
        .modal-header
          .button.close aria-label="Close" data-dismiss="modal" type="button" ×
        .modal-body
          = form_tag user_sessions_path, method: :post do
            .form-container
              .form-row
                .h1 Sign In
              .form-row 
                = label_tag :email
                br
                = text_field_tag :email, nil, class:'input-box'
              .form-row 
                = label_tag :password
                br
                = password_field_tag :password, nil, class:'input-box'
              .form-row.checkbox
                label
                  = check_box_tag :remember, params[:remember], true
                  | Remember me
              .form-row 
                  = submit_tag "Login"
              .form-row 
                = link_to 'Forgot Password?', new_password_reset_path

app/views/shared/_sign_up.html.slim
#register-modal.modal.fade tabeindex="-1" role="dialog"
  .modal-dialog role="document"
    .modal-content
      .modal-header
        .button.close aria-label="Close" data-dismiss="modal" type="button" ×
      .modal-body
        - if @user
          = form_for @user, url: users_path, method: :post do |f|
            .form-container
              
              .form-row
                .h1 Sign Up
              .form-row 
                =f.label :email
                br
                =f.email_field :email, required: :true, class:'input-box'
              .form-row
                =f.label :password
                br
                =f.password_field :password, required: :true, class:'input-box'
              .form-row
                =f.label :password_confirmation
                br
                =f.password_field :password_confirmation, required: :true, class:'input-box'
              = f.fields_for :user_profile do |builder|
                .form-row
                  = builder.label :first_name
                  br
                  = builder.text_field :first_name, required: :true, class:'input-box'

                .form-row
                  = builder.label :last_name
                  br
                  = builder.text_field :last_name, class:'input-box'

                .form-row
                  = builder.label :contact_no
                  br
                  = builder.text_field :contact_no, required: :true, class:'input-box'

              .form-row
                =f.submit "Submit", class: "btn btn-primary"